--- 
require: []

rackup: screen.ru
daemonize: true
timeout: 30
log: log/thin.log
address: 127.0.0.1
servers: 1
environment: production
max_persistent_conns: 512
port: 3100
max_conns: 1024
wait: 30
chdir: /var/apps/screen
pid: tmp/pids/thin.pid
